### PR TITLE
Support handle ping frames

### PR DESCRIPTION
**Pull request by vincentjames501**
- Partially address issue #350

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Looks good, thank you Vincent- merging manually now! :+1:

**Comment by ptaoussanis** [comment]
Appears to break unit tests, sorry:

```
lein test org.httpkit.ssl-bench

lein test org.httpkit.test-util

lein test org.httpkit.utils-test

lein test org.httpkit.ws-test

lein test :only org.httpkit.ws-test/test-websocket-ping-handler

ERROR in (test-websocket-ping-handler) (WebSocketClient.java:121)
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.Exception: pong frame expected, instead of TextWebSocketFrame(text: ECHO: TEST)
 at org.httpkit.ws.WebSocketClient.ping (WebSocketClient.java:121)
    org.httpkit.ws_test$fn__10980.invokeStatic (ws_test.clj:132)
    org.httpkit.ws_test/fn (ws_test.clj:130)
    clojure.test$test_var$fn__7983.invoke (test.clj:716)
    clojure.test$test_var.invokeStatic (test.clj:716)
    clojure.test$test_var.invoke (test.clj:707)
    clojure.test$test_vars$fn__8005$fn__8010.invoke (test.clj:734)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    clojure.test$test_vars$fn__8005.invoke (test.clj:734)
    org.httpkit.ws_test$eval10858$fn__10859.invoke (ws_test.clj:91)
    clojure.test$compose_fixtures$fn__7977$fn__7978.invoke (test.clj:693)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    clojure.test$compose_fixtures$fn__7977.invoke (test.clj:693)
    clojure.test$test_vars.invokeStatic (test.clj:730)
    clojure.test$test_all_vars.invokeStatic (test.clj:736)
    clojure.test$test_ns.invokeStatic (test.clj:757)
    clojure.test$test_ns.invoke (test.clj:742)
    clojure.core$map$fn__4785.invoke (core.clj:2646)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:688)
    clojure.core$next__4341.invokeStatic (core.clj:64)
    clojure.core$reduce1.invokeStatic (core.clj:925)
    clojure.core$reduce1.invokeStatic (core.clj:915)
    clojure.core$merge_with.invokeStatic (core.clj:2950)
    clojure.core$merge_with.doInvoke (core.clj:2942)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.test$run_tests.invokeStatic (test.clj:767)
    clojure.test$run_tests.doInvoke (test.clj:767)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    user$eval87$fn__146$fn__177.invoke (form-init766643446586282680.clj:1)
    user$eval87$fn__146$fn__147.invoke (form-init766643446586282680.clj:1)
    user$eval87$fn__146.invoke (form-init766643446586282680.clj:1)
    user$eval87.invokeStatic (form-init766643446586282680.clj:1)
    user$eval87.invoke (form-init766643446586282680.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6927)
    clojure.lang.Compiler.eval (Compiler.java:6917)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.Compiler.loadFile (Compiler.java:7317)
    clojure.main$load_script.invokeStatic (main.clj:275)
    clojure.main$init_opt.invokeStatic (main.clj:277)
    clojure.main$init_opt.invoke (main.clj:277)
    clojure.main$initialize.invokeStatic (main.clj:308)
    clojure.main$null_opt.invokeStatic (main.clj:342)
    clojure.main$null_opt.invoke (main.clj:339)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

Ran 80 tests containing 6893 assertions.
0 failures, 1 errors.
Tests failed.
```

Would be happy to re-merge if you can fix, thanks!

**Comment by vincentjames501** [comment]
Weird, that's my test and it used to pass! I'll take a look a little later.

**Comment by vincentjames501** [comment]
I just rebased, but the tests appear to work just fine for me?

```
$ lein do clean, test
...
Ran 80 tests containing 6911 assertions.
0 failures, 0 errors.
```

**Comment by ptaoussanis** [comment]
You're correct, thanks for checking- I'd neglected to run `lein clean`. Will re-merge shortly.

**Comment by ptaoussanis** [comment]
Merged manually :+1:

**Pull request closed without merging**
