### PR TITLE
Make MappedByteBufferSize threshold configurable via option

### PR DESCRIPTION
**Pull request by ikappaki**
Hi,

please find in this PR a potential but naive solution for the locking issue described in #478 for making the file size threshold configurable.

The patch introduced a new `:file-mapped-thresh` that lets the developer choose the file size threshold above of which http-kit will choose to memory map Files before serving them to the client.

This will at least allow a developer to prevent file locking of large artefacts during development by having them specify the threshold of which files are mapped into memory.

It has been tested with the  test project submitted in #478, with a slight modification as below fore setting the threshold to 6 MB:

in *src/issue/http_kit_mapped_file.cljs:-main*:
```clojure
     ;; server parameters
     {:port port
      :file-mapped-thresh (* 1024 1024 6)}
```
Thus, requesting a file of 4 Mb at http://localhost/4

and then deleting it works ok without errors:
```
>del 4.js
```

But, requesting a file of 6 Mb at http:///localhost/6

and then deleting it results to an error:
```
>del 6.js
The process cannot access the file because it is being used by another process.
```

i.e. the threshold configured at start up has taken effect.

Thanks

### CODE REVIEW

**Comment by bsless** [comment]
Instead of setting a public field, what do you think about these two other possible solutions:
- set the threshold via a JVM property
- set via delayed inner class initialization, similar to [this](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/ClientSslEngineFactory.java#L15)

**Comment by ikappaki** [comment]
> Instead of setting a public field, what do you think about these two other possible solutions:

Sure. I think the JVM property option is a better solution, appears to be a better fit for setting low level options.

(My Java writing skills are almost non-existent, so feel free to scrutinize the code)
 
>     * set the threshold via a JVM property

Would something like this do?

```java
public class HttpUtils {

    // Files are memory mapped when above this threshold.
    private static int MAPPED_BUFFER_THRESH_SIZE_BYTES = initMappedThreshold();

    // Returns the threshold in bytes after which files should be
    // memory mapped for efficiency, as calculated from the
    // org.http-kit.mapped-file-threshold jvm property (defaults to 20
    // MB).
    private static int initMappedThreshold()
    {
        return 1024 * 1024
            * Integer.getInteger("org.http-kit.mapped-file-threshold", 20);
    }
    // ...
    public static ByteBuffer readAll(File f) throws IOException {
        int length = (int) f.length();
        if (length >= MAPPED_BUFFER_THRESH_SIZE_BYTES) {
            FileInputStream fs = new FileInputStream(f);
            MappedByteBuffer buffer = fs.getChannel().map(MapMode.READ_ONLY, 0, length);
            fs.close();
            return buffer;
        } else {
            return ByteBuffer.wrap(readContent(f, length));
        }
    }
   //  ...
}

```


>     * set via delayed inner class initialization, similar to [this](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/ClientSslEngineFactory.java#L15)

Sorry, can't see how to do this without overcomplicating the code (an inner Properties class with a setter and getter for the field in question, instantiated via an inner static Properties field?). Example implementation sketch is most welcome.

Thanks!

**Comment by ikappaki** [comment]
Hi,

I have made the memory mapped size threshold configurable via a new `org.http-kit.memmap-file-threshold` jvm property as per @bsless  suggestion. Could someone please review the change?

It passes the test

e.g. Configure the test server to only memory map files above 2MB
```
clojure -J-D"org.http-kit.memmap-file-threshold=2" -M -m issue.http-kit-mapped-file
```

Test server creates a 1MB file with http://localhost:3003/1, and user can delete it from the command prompt
```
>del 1.js
```

Test server creates a 2MB file with http://localhost:3003/2, but user can't delete it from the command prompt (file is locked)
```
>del 2.js
The process cannot access the file because it is being used by another process.
```

Thanks,

**Comment by ikappaki** [comment]
> 
> 
> @ikappaki Thanks so much for the report, and for your PR! Looks promising, though I unfortunately don't have the opportunity to review in detail today. Will try take a closer look at this for next release. Otherwise someone else can hopefully help review before then!

Great thanks! I've changed the PR's title for clarity.

**Comment by ptaoussanis** [comment]
This will be included in the next (v2.7) dev branch, thanks!

**Pull request closed without merging**
