### PR TITLE
Minimal fix to add SNI support to client

### PR DESCRIPTION
**Pull request by sattvik**
Here is an initial effort at resolving #187.  I welcome any feedback, since I
am not very familiar with the http-kit code or the async NIO library.

This works for my particular situation, but there are a couple of caveats:
1. This code is Java 8 only.  If there is a need to support older versions of
   Java, this logic will need to be wrapped.
2. It’s possible that a bad hostname could result in an
   `IllegalArgumentException`.  Is it better for that to be allowed to bubble
   up or should it be swallowed and the SNI support disabled.

Lastly, is this the righ insertion point for adding the SNI support?  I do
not know if there could be any race conditions or shared state that could
result from this.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
@sattvik Hi Daniel, thanks a lot for this. Looks promising, and definitely keen to get SNI support in.

Will try schedule a look w/in the next week or two. 

Otherwise, feedback from anyone would be welcome in the meantime.

**Comment by juhakaremo** [comment]
Thank you, Daniel.

I tested this patch and as far as I can tell this patch fixes the SNI issue. Without this fix we are unable to connect to our AWS deployed services using http-kit. 

I will not comment on the actual code changes since I'm not that familiar with http-kit code base or SNI.

**Comment by stevenschlansker** [comment]
hi @ptaoussanis we just ran into a production incident where missing this feature was a contributing factor.  So our feedback is, "this feature is important!" 😄 The code looks reasonable to me (given not really knowing all that much about `http-kit` or Clojure)

**Comment by soumyapaul30** [comment]
What is the SLA to get this fix available for us to use? This is very much in need at the moment.

**Comment by taffowl** [comment]
Also just hit this issue also whilst trying to do a get request to aws apigateway using `http-kit`

**Comment by ptaoussanis** [comment]
@sattvik: Hi Daniel, I'm really sorry for taking so long to look at this - really do appreciate your efforts on this!

> It’s possible that a bad hostname could result in an IllegalArgumentException. Is it better for that to be allowed to bubble up or should it be swallowed and the SNI support disabled.

I believe surfacing the exception is probably better.

> This code is Java 8 only. If there is a need to support older versions of Java, this logic will need to be wrapped.

So this may unfortunately be a blocker since I'd rather we not break JVM compatibility if we can avoid it. 

Is there any way I may be able to request a wrapper so that only those wishing to use the new SNI support require Java >= 8? I.e. we retain support for older JVM versions for those not needing SNI?

May also request a unit test if possible to exercise the SNI support?

If you (or someone else) can get a modified PR up, I'll make sure to get it merged right away!

Again, sincere thanks.

**Comment by kumarshantanu** [comment]
> Is there any way I may be able to request a wrapper so that only those wishing to use the new SNI support require Java >= 8? I.e. we retain support for older JVM versions for those not needing SNI?

I have submitted https://github.com/http-kit/http-kit/pull/335 to decouple Java 8 changes from SSLEngine customization in the client.

**Comment by ptaoussanis** [comment]
Hi @kumarshantanu, thank you! Will try look at your PR at the weekend!

**Comment by tdg5** [comment]
Is there anything folks in the community can do to help get this patch merged sooner?

- [x] It seems like @kumarshantanu has [taken a stab at addressing the Java 8 dependency](https://github.com/http-kit/http-kit/pull/335)
- [x] From what I can tell the concern regarding the `IllegalArgumentException` when a bad hostname is encountered doesn't require any additional work as the current behavior is the desirable behavior.
- [ ] A unit test

Anything else outstanding that would help move this along?

**Comment by ptaoussanis** [comment]
@tdg5 Hi Danny, sincere apologies for the slow response- will try my best to get this merged tonight after work!

**Comment by ptaoussanis** [comment]
Merged! Released on Clojars as `[http-kit "2.3.0-alpha3"]` :-)

**Comment by icambron** [comment]
@ptaoussanis I'm a bit confused. From the discussion above, it sounds like you were rejecting this change for being Java 8-only and were intending to merge #335 to let the caller set up SNI and inject it. But you merged this one and not that one. Is this a) a mistake and you meant to merge the other one or b) a change in your decision re: Java 8?

**Comment by ptaoussanis** [comment]
@icambron Hi Isaac, thanks for checking - option a): this was indeed a mistake on my part. Had only skimmed it and misunderstood the comment by https://github.com/http-kit/http-kit/pull/311#issuecomment-324423610.

Will try take a proper look at this this weekend. Apologies for the confusion.

**Comment by ptaoussanis** [comment]
Okay, just cut https://github.com/http-kit/http-kit/releases/tag/2.3.0-alpha4!

**Pull request closed without merging**
