### PR TITLE
`[wiki]` Add client page from website

### PR DESCRIPTION
**Pull request by harold**
- Minor re-arrangement/cleanups/typo fixes

### CODE REVIEW

**Comment by harold** [comment]
I took some time and moved the information from this page: https://http-kit.github.io/client.html

Into the wiki.

hth, thanks again for this project and everything else.

**Comment by ptaoussanis** [comment]
@harold Thanks for this Harold, that's great!

Currently doing some work on http-kit weekend, will get this merged in the next couple days 👍

**Comment by harold** [comment]
Very cool, no rush.

**Comment by ptaoussanis** [comment]
Merged manually, thanks again!

**Comment by harold** [comment]
You're welcome - long live http-kit.

**Pull request closed without merging**
