### PR TITLE
Adding fix to allow https requests through http-proxy

### PR DESCRIPTION
**Pull request by jbristow**
I need some eyes on it to a) figure out if I actually solved the problem and b) make sure I'm testing this right.

I can't get this to work in mitmproxy so I suspect I missed something.  Either I haven't configured mitmproxy properly, or I've missed something else that needs to be changed.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi Jon, thanks for your efforts. Could I perhaps ask for a short summary/reminder of what the particular problem is here that you're trying to address?

Are there other ways of addressing this problem? Is it necessary to mod http-kit?

Thanks!

**Comment by ptaoussanis** [comment]
Update: just saw that this relates to #280

**Comment by jbristow** [comment]
The main problem I saw is that when you connect to an http proxy with http-kit, (say it's on my-proxy:80) and then try to connect to https://www.google.com, the request is still marked as https, so this code fails:


```java
// src/java/org/httpkit/client/HttpsRequest.java lines 135-141
    public void recycle(Request old) throws SSLException {
        super.recycle(old);
        this.engine = ((HttpsRequest) old).engine;
        this.handshaken = true;
        wrapRequest(); // prepare for write
    }
```

**Comment by ptaoussanis** [comment]
Closing with #291

**Pull request closed without merging**
