### PR TITLE
Added a getCount method to BytesInputStream

### PR DESCRIPTION
**Pull request by MysteryMachine**
At my company, we use the length of inputs to do load estimation on our backend. As of right now, there is no easy way to access the length of a BytesInputStream other than calling toString on it, and parsing out the returned length. 

This PR provides an accessor to count in BytesInputStream. Since it is already exposed in toString, I figured it would not be a problem.

I'm eager to get this in, let me know if there are any changes you'd like! Or, if you'd prefer some alternative approach, let me know and I'll do things your way.

### CODE REVIEW

**Comment by venantius** [comment]
This seems fine to me. Thanks for submitting.

**Comment by ptaoussanis** [comment]
Thanks both!

**Comment by ptaoussanis** [comment]
@venantius May I request that we merge as with the [previous style](https://github.com/http-kit/http-kit/commits/master) when possible? This project gets many small contributions, and having everything indexed on master saves me a lot of time if we need to do bisecting, or when cutting releases, etc. 

Cheers! :-)

**Comment by venantius** [comment]
@ptaoussanis of course, sorry about that. It occurred to me that I should have used your format almost immediately after I merged it :(.

**Comment by ptaoussanis** [comment]
Zero problem. Appreciate all your help :-)

**Pull request merged**
