### PR TITLE
CHANGED - modify http server loop error

### PR DESCRIPTION
**Pull request by tweeks-reify**
Wanted to clarify to ensure this error is seen as actionable

### CODE REVIEW

**Comment by ptaoussanis** [comment]
@tweeks-reify Hi there, thanks for this!

While I agree that "should not happen" is too vague, I wonder if we could maybe do even better than "investigate this error"?

What kind of error were you running into here exactly?

**Comment by tweeks-reify** [comment]
Thanks @ptaoussanis.  Our issue was caused by running out of Direct Buffer Memory in the JVM (which was captured in the stack trace).  Open to suggestions but maybe even `see stracktrace:` or something like that to indicate there are more details?

**Comment by ptaoussanis** [comment]
@tweeks-reify That sounds reasonable to me 👍 
So "http server loop error, see stack trace for details"?

**Comment by ptaoussanis** [comment]
👍 Will merge for v2.7 next time I'm doing batched work on http-kit - thanks!

**Comment by ptaoussanis** [comment]
Merged manually, closing 👍

**Pull request closed without merging**
