### PR TITLE
Fix ssl engine factory init race condition

### LINKED ISSUE #456: [Regression] #434 introduced race condition in initialization of client context
Hi,
Before #434 the SSL context was initialized once during class initialization. The client context is initialized during `trustAnybody`.
If `trustAnybody` is called in parallel before initialization finishes, it can override the clientContextImpl initialization and throw
`SSLContextImpl is not initialized`.
In short, `trustAnybody` is not thread safe.
Stacktrace:
```
java.lang.IllegalStateException: SSLContextImpl is not initialized
at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(SSLContextImpl.java:191)
at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:329)
at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:26)
at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
at org.httpkit.client$request.invokeStatic(client.clj:242)
```

### PR DESCRIPTION
**Pull request by bsless**
Closes #456

### CODE REVIEW

**Comment by bsless** [comment]
Hi,
This PR should fix the race condition introduced in #434 and close #456.
Would like to test it out more rigorously in case I missed anything. I'll ask some colleagues to look it over, too.
Thanks,
Ben

**Comment by borkdude** [comment]
Looks good to me!

**Comment by bsless** [comment]
Hi @borkdude @ptaoussanis I updated the PR with a different implementation based on https://stackoverflow.com/questions/8297705/how-to-implement-thread-safe-lazy-initialization/8297830#8297830

Please let me know what you think

**Comment by borkdude** [comment]
@bsless Seems good to me. I hope this will not break GraalVM native compatibility, but I can test this with a snapshot version. If you can deploy a test version of this to clojars, I can try it in babashka for example.

**Comment by borkdude** [comment]
@bsless Never mind, I can just do a local lein install.

**Comment by borkdude** [comment]
@bsless @ptaoussanis This seems to break native-image. Maybe @alekcz knows a solution since he fixed a related problem before.

```
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by
	reading field java.security.SecureRandom.secureRandomSpi of
		constant java.security.SecureRandom@6eed8add reached by
	reading field sun.security.ssl.SSLContextImpl.secureRandom of
		constant sun.security.ssl.SSLContextImpl$TLSContext@555ff08d reached by
	reading field javax.net.ssl.SSLContext.contextSpi of
		constant javax.net.ssl.SSLContext@1084eddb reached by
	scanning method org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
Call path from entry point to org.httpkit.client.ClientSslEngineFactory.getContextInstance():
	at org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
	at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:33)
	at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
	at org.httpkit.client$request.invokeStatic(client.clj:242)
	at org.httpkit.client$request.doInvoke(client.clj:180)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at babashka.main.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by
	reading field java.security.SecureRandom.secureRandomSpi of
		constant java.security.SecureRandom@6eed8add reached by
	reading field sun.security.ssl.SSLContextImpl.secureRandom of
		constant sun.security.ssl.SSLContextImpl$TLSContext@555ff08d reached by
	reading field javax.net.ssl.SSLContext.contextSpi of
		constant javax.net.ssl.SSLContext@1084eddb reached by
	scanning method org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
Call path from entry point to org.httpkit.client.ClientSslEngineFactory.getContextInstance():
	at org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
	at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:33)
	at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
	at org.httpkit.client$request.invokeStatic(client.clj:242)
	at org.httpkit.client$request.doInvoke(client.clj:180)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at babashka.main.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:768)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by
	reading field java.security.SecureRandom.secureRandomSpi of
		constant java.security.SecureRandom@6eed8add reached by
	reading field sun.security.ssl.SSLContextImpl.secureRandom of
		constant sun.security.ssl.SSLContextImpl$TLSContext@555ff08d reached by
	reading field javax.net.ssl.SSLContext.contextSpi of
		constant javax.net.ssl.SSLContext@1084eddb reached by
	scanning method org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
Call path from entry point to org.httpkit.client.ClientSslEngineFactory.getContextInstance():
	at org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
	at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:33)
	at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
	at org.httpkit.client$request.invokeStatic(client.clj:242)
	at org.httpkit.client$request.doInvoke(client.clj:180)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at babashka.main.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	... 8 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1647)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1397)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1358)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1317)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1829)
```

**Comment by borkdude** [comment]
@bsless FYI: this was the fix that @alekcz made for native-image a while ago:

https://github.com/http-kit/http-kit/commit/c3e983d618c054318fee44ea7f16e5f7cb8ba46a

**Comment by bsless** [comment]
damn, I tried to fix it without breaking the native image compatibility. When I checked it seemed like the SSL wasn't initialized on the heap. I did check by just throwing in a print statement in the class though, so not perfect.
I'm aware of the native image fix, it's what introduced the race condition in the first place.
Can you share how you checked it against native-image? Got some baseline repo? It would be better if I check if offline next time before pushing.

**Comment by borkdude** [comment]
@bsless Will provide you with a repro. First let me try one more thing: maybe `"--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory"` will help...

**Comment by bsless** [comment]
@borkdude fingers crossed. It's really down to messing around with class initialization time and order. The inner class doesn't get initialized on the JVM until it is accessed, which should have solved the issue.

**Comment by borkdude** [comment]
@bsless It didn't seem to work.

You can repro this by building babashka with your local httpkit dep installed with `lein install` and then changing the `project.clj` of babashka.

Build instructions are here: https://github.com/babashka/babashka/blob/master/doc/build.md

Let me know if you have any questions getting started.

**Comment by bsless** [comment]
@borkdude I think I got it!
Needed to delay the initialization of the inner class to runtime as well
```
       "--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory"
       "--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory\$SSLHolder"
```
Then tested the generated image:
```
user=> (require '[org.httpkit.client :as http])
nil
user=> (http/get "https://google.com")
#object[org.httpkit.client$deadlock_guard$reify__18716 0x27d18bed {:status :pending, :val nil}]
user=> (deref *1)
{:opts {:method :get, :url "https://www.google.com/ ,,,,, ;; elided
```
Made sure to use exactly the same graalvm version as you do for babashka.
Can you please check if this works for you as well?

**Comment by borkdude** [comment]
@bsless Cool, only the second flag seems to be necessary:

```
"--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory\$SSLHolder"
```

```
./bb -e "(:status @(org.httpkit.client/get \"https://google.com\"))"
200
```

**Comment by borkdude** [comment]
@ptaoussanis FWIW, I think this is good for merge...

**Comment by ptaoussanis** [comment]
👍 Thanks all, will take a proper look at this thread the next time I'm batching some open-source work (hopefully within the next week or so).

**Comment by ptaoussanis** [comment]
Merged manually- thanks for this (and all the assistance!) 🙏

**Pull request closed without merging**
