### PR TITLE
Add support for Unix Domain Sockets

### PR DESCRIPTION
**Pull request by kipz**
This draft hacks in support for Unix Domain Sockets in client and server to initiate a discussion around the approach, especially around whether it's feasible to have a JDK17 only version...

Any ideas or feedback most welcome.

See #461 for a discussion around why people might like UDS support

### CODE REVIEW

**Comment by borkdude** [comment]
Very interesting. Another interesting experiment might be to leverage the JDK19 virtual threads :)

**Comment by kipz** [comment]
Yeah, it's interesting that it's mostly a search and replace of `InetSocketAddress` with `SocketAddress` :)

**Comment by kipz** [comment]
@ptaoussanis et al - I'm thinking of updating this PR add support for custom address/socket handling when creating clients/servers, and then create a separate mini-library for JDK17+ for unix socket support, but I'm wondering whether or not it's crucial to maintain the current Java APIs? Are they considered part of the public API or not? It's not the end of the world if they are, it's just that it'll end up much cleaner if I can make some changes. WDYT?

**Comment by ptaoussanis** [comment]
@kipz Hi James,

> I'm wondering whether or not it's crucial to maintain the current Java APIs? Are they considered part of the public API or not?

I can't say off-hand, sorry. It might depend on what specific parts of the API you have in mind. Do the parts in question have any docs/comments to indicate whether they're public?

If there's no guidance, a break could well be warranted - depending approximately on:

- Does a web search turn up any obvious users?
- How user-facing is the particular API? The more obscure, the less likely that someone's depending on it.
- If we believe it's reasonable that someone might be depending on the particular API - how easy would it be for them to migrate, and how easily could we document the necessary migration?
- How significant is the benefit of breaking?

**Re: the PR in general**, the clearer the following info can be for me and other reviewers, the easier it'll make reviewing:

1. What's the intended benefit of the PR? Can we be precise? If performance is a significant motivator, can the effect of the PR be quantified?

2. Are there any _known disadvantages_ of the PR? E.g. - are pre-existing users potentially impacted? If so, how? Will anyone be broken? How badly and under what conditions? Is there any particular new maintenance burden we might be incurring?

3. What's our level of confidence that the above disadvantages are exhaustive, i.e. that we're not missing anything important? Are there any particular areas of possible concern that might warrant further input or digging?

Really appreciate all your effort on this 👍
Cheers :-)

**Comment by kipz** [comment]
@ptaoussanis that's my answer right there! :) I can extend what is there without breaking anything!

**Comment by kipz** [comment]
I'll re-open with details of the new approach.

**Pull request closed without merging**
