### PR TITLE
RFC: Adding shutdown hooks

### PR DESCRIPTION
**Pull request by alekcz**
This pull request adds 4 things:
1. Test whether the server is running: _This is done by monitoring the thread state using `isAlive()` for threads that have started_ 
2. Test whether the server is shutting down: _This done by monitoring `AtomicBoolean` used in Graceful shutdown (introduced in #399)_
3. Synchronous server shutdown: _This is done by waiting for the server thread to `.join()`_
4. Trigger a callback after shutdown: _This is done by passing a Clojure function as a `Runnable` into `.stop`. To preserve backward compatibility the  `.stop` has been overloaded [here](https://github.com/alekcz/http-kit/blob/6f2c47d2b71ce1b6b8ca1dab3e482ff806f77414/src/java/org/httpkit/server/HttpServer.java#L397)._

```clojure
;; example usage
(server :state :running?) ;;1
(server :state :shutting-down?) ;;2
(server :synchronous true) ;;3
(server :timeout 500  :synchronous true) ;;3
(server :callback callback-fn) ;;4
(server :timeout 500 :callback callback-fn) ;;4
(server) ;; still available
(server :timeout 500) ;; still available
```
This aims to solve #186.

(Also created a Github actions to make contributions easier for new contributors)

### CODE REVIEW

**Comment by alekcz** [comment]
@ptaoussanis any feedback?

**Comment by ptaoussanis** [comment]
Hi Alexander, thanks so much for this! Sincere apologies for taking so long to reply.

I'd like to review this properly, but am seriously time-constrained recently. So as an efficiency measure, end up trying to batch most of my open-source work.

Will try take a proper look at this next time I'm reviewing PRs for cutting the next http-kit release.

Realistically may be a few months unless an urgent issue comes up, so might temporarily suggest a fork if you need this sooner.

Really appreciate your assistance! Cheers :-)

**Comment by alekcz** [comment]
@ptaoussanis no stress. I completely understand. This is a labour of love after all. 
I'll wait till then. Thanks for all your work on this.

**Comment by ptaoussanis** [comment]
Hi Alexander, finally got around to reviewing + merging!

Thanks again for this! 

Some constructive feedback for future PRs-

Please try to prepare your commits for easier reviewing, for example:

- Try to avoid unnecessary/orthogonal changes (or at least group them in dedicated commits).
	- This incl. stuff like whitespace/formatting changes, status badges, etc.
- Try to avoid including unnecessary merge commits.
- Try to avoid disjoint but related commit sequences, e.g.: commit 1, 2, 3, 4 where #3 corrects details in #1 and #4 corrects details in #2. This makes it difficult / time-consuming to understand a PR sequentially.
	- This is especially challenging to review if #3 also includes stuff unrelated to the correction of #1.

Basically: it's super helpful for your reviewer if it's possible for them to go through your commits sequentially and have each commit be (as much as possible) logically self-contained, and free of incidental/temporary work-in-progress stuff that isn't ultimately relevant to the review (things like abandoned ideas, bugs that you already discovered+fixed, etc.).

It can also be really helpful to start with a very clear outline of what precisely you're trying to achieve. This is helpful both for your reviewer (since it helps them review objectives in abstract before looking at implementation details), and it's helpful for you (since it helps quantify how well objectives have been met and if the unit test coverage is precise + effective).

Running `git rebase -i` on your private branch before opening a PR can be quite useful for these kinds of things.

Hope that makes some sense?

Also if you have an opportunity, would be great to get a second set of eyes on the current implementation:
https://github.com/http-kit/http-kit/commit/ec5bb8f55ae0afa97535647f02f2c5a26e3484ce?w=1

Did this in a rush. Quick summary of relevant changes:

- `run-server` can now return an `HttpServer` object via the `:legacy-return-value? false` opt.
  - The old return value fn-with-meta wasn't ideal, esp. if we're introducing more features.

- Several new fns introduced to operate on `HttpServer` objects:
  - `server-port`, `server-status`, server-stop!`.
- `server-stop!` returns a promise that can be dereffed for blocking semantics (solving #186).
- `server-stop!` is now ~idempotent.
- `server-status` returns e/o `{:stopped :running :stopping}`.

Cheers!

**Comment by alekcz** [comment]
Thank you for the feedback. Much appreciate. I'm with you. I'll keep that in mind next time. 

Had a look at the current implementation.
- The new approach makes sense and is scalable. 
- Returning promise on stop will make writing tests in libraries using http-kit much easier. (I've done some dodgy things in my tests to get around this in the past)
- My only comment really is stylistic, I'd have gone for the threading macro here for readability: https://github.com/http-kit/http-kit/blob/ec5bb8f55ae0afa97535647f02f2c5a26e3484ce/src/org/httpkit/server.clj#L27 

Thanks again for the feedback.

I can close this PR now right?

**Comment by ptaoussanis** [comment]
Awesome, thank you Alexander 👍  I'll close now, and will cut a release shortly.

**Pull request closed without merging**
