### PR TITLE
proxy support

### PR DESCRIPTION
**Pull request by davidkazlauskas**
Made basic http proxy support for my project, feel free to merge

### CODE REVIEW

**Comment by mhjort** [comment]
Would it be possible to add a test case for this feature? I know it's not trivial in this case. However, it would be really nice to get some test coverage on new features.

**Comment by danielcompton** [comment]
`mitmproxy` is one tool I know of that is relatively straightforward to setup as a proxy.

**Comment by jbristow** [comment]
I'm not sure this works.  I created a quick test to see if I could add a proxy server.  It works for clj-http, but not http-kit.

Can someone look at this to verify what I'm seeing? I'm still spinning up, so if someone can point me where I went wrong, please do so! 

https://github.com/jbristow/http-kit/commit/94002782da6caeaa442272a1ccaf6f991c0a9e77

**Comment by mhjort** [comment]
Hi, I checked your test code. And send you comments. Problem was that that proxy was not running in correct port. It worked with clj-http because it seems to ignore the proxy configuration if proxy cannot be connected.

And this new http-kit proxy implementation fails if proxy cannot be connected. Personally I think this is correct way in this case

**Comment by mhjort** [comment]
Also I tested with mitmproxy and verified that this actually works. If you make changes to test code that I mentioned they should pass.

**Comment by davidkazlauskas** [comment]
Thanks for testing this out, sorry for being lazy :(

**Comment by davidkazlauskas** [comment]
I see there's a travis fail, I tried to clone at that commit, first tried lein test org.httpkit.client-proxy-test, then just lein test and got no errors. I see there's a timeout stuff, could travis be retried just in case and can anyone verify that tests pass for them at 680ff1d1a9c7586a0d96104cb5bea997100108ab commit?

**Comment by mhjort** [comment]
I tested locally. Tests pass. Also trying rerun in Travis now. We have been having problems with Travis and async tests

**Comment by mhjort** [comment]
After retry tests pass in Travis. Thanks @davidkazlauskas  and @jbristow 

Only one last thing. Could you be cleanup git history a bit (squash some commits together with meaningful commit msgs). The code looks good now but it consists of 9 different commits. After that this could be merged in.

**Comment by davidkazlauskas** [comment]
Squashed down tests to single commit, still the timeout stuff in travis though.

**Comment by mhjort** [comment]
Thanks. Two retries in Travis helped. I will merge this.

**Comment by lensgolda** [comment]
Please add documentation for proxy support

**Pull request merged**
