### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by venantius**
This PR encompasses a number of disparate cleanup efforts, largely oriented around the test code. 

Some aspects of this:
 * Type hints to reduce the reflection warnings
 * Fixing indentation
 * Minor idiomatic fixes
 * Re-enabling clobbered tests and cases where assertions should have existed but didn't

### CODE REVIEW

**Comment by venantius** [comment]
I think this is a fairly harmless update, but code review is always nice. @ptaoussanis, any chance you could give this a quick glance at some point?

**Comment by mhjort** [comment]
I can help out with this.

**Comment by venantius** [comment]
Thanks @mhjort !

**Comment by ptaoussanis** [comment]
Looks good to me, thanks!

**Pull request merged**
