### PR TITLE
Update HttpServer.java

### PR DESCRIPTION
**Pull request by Thingographist**
64Kb

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi there, could you explain a little what the motivation is here? Thanks

**Comment by ptaoussanis** [comment]
Closing since this seems to be a duplicate of #236 (already merged)

**Comment by ptaoussanis** [comment]
Merged, thanks!

**Comment by hiteshjasani** [comment]
@Thingographist, @ptaoussanis  Sorry, I realize this has already been merged in, but can you comment on why this change was desired?

[RFC 1323](http://www.ietf.org/rfc/rfc1323.txt) defines Window Scale Options which

> The scale factor is limited to a power of two and encoded logarithmically,
> so it may be implemented by binary shift operations.

In other words, all major OS's provide the ability to define TCP Window Sizes beyond the original 16 bits originally provided in the header.  So TCP windows can indeed be truly `65,536 (2**16)` in size very easily.  Defining a capacity for this buffer that is not a power of two would seem to lead to additional buffer reads in some cases, a wasted byte to memory alignment padding and possible [misaligned memory access](https://www.kernel.org/doc/Documentation/unaligned-memory-access.txt).

**Pull request closed without merging**
