### PR TITLE
wiki/3-Server.md: add writeup for websockets (was -> "start writeup for WebSocket handling")

### PR DESCRIPTION
**Pull request by jf**
as promised in https://github.com/http-kit/http-kit/issues/570#issuecomment-2143496684

I wasn't too sure about the exact placement or structure, but figured I could just start, and you can then edit or shift as necessary. In that vein, I have only the barest of intros for the 2 approaches, and the main body of my work is in the demo code instead.

### CODE REVIEW

**Comment by jf** [comment]
FYI I figured out the code for using WebSockets in Ring. I'm afraid this isn't the best code for showcasing / contrasting the 2 approaches though.

It looks like (at least for me, based on my reading) that one key difference is in how errors are handled when you send a message: for the unified API, you can handle it without callbacks, but for Ring, you'll need to handle it in a callback.

As mentioned at https://github.com/http-kit/http-kit/issues/570#issuecomment-2143868478, I will really need your help to really do the explanation and contrasting justice.

**Comment by jf** [comment]
an update: I added the beginnings of some notes contrasting the 2 approaches.

A couple of notes:
1. I decided to refrain from saying "HTTP long-polling/streaming", but only "HTTP long-polling", because it seems that "HTTP streaming" can (is?) be associated with streaming media over HTTP, which is its own separate thing (especially if you get into [adaptive bitrate streaming](https://www.cloudflare.com/learning/video/what-is-adaptive-bitrate-streaming/)).
2. as usual, please vet the accuracy of my points.

Thank you.

**Comment by ptaoussanis** [comment]
@jf Thanks Jeffrey! I'll take a closer look at this next time I'm on batched http-kit work.

Definitely feel free to keep things short/simple; something basic would already be a big upgrade on what we have now 👍

Really appreciate your help on this.

**Comment by ptaoussanis** [comment]
Merged manually, thanks again Jeffrey! 🙏

**Comment by jf** [comment]
thanks. Comparing before and after, I see how you've improved the code... (and even the formatting?)

One question: this is more out of curiosity, but in my PR, I do note that Ring's websocket API is experimental (as per https://github.com/ring-clojure/ring/wiki/WebSockets). Is this not the case?

**Comment by ptaoussanis** [comment]
> Comparing before and after, I see how you've improved the code... (and even the formatting?)

Nothing significant, just some superficial changes to hopefully help keep things consistent with other code style in the wiki.

> One question: this is more out of curiosity, but in my PR, I do note that Ring's websocket API is experimental (as per https://github.com/ring-clojure/ring/wiki/WebSockets). Is this not the case?

I was under the impression that the API became stable at some point, though I may very well be mistaken! Ring is currently at [1.12.2](https://github.com/ring-clojure/ring/blob/master/CHANGELOG.md), though now that you mention it - the CHANGELOG doesn't make any specific mention of the API dropping its "experimental" status.

The current [protocol code](https://github.com/ring-clojure/ring/blob/master/ring-websocket-protocols/src/ring/websocket/protocols.clj) doesn't appear to be obviously marked as experimental, at least.

Would be happy to add the mention of "experimental" back in if I'm wrong! Thanks for checking on that.

**Pull request closed without merging**
